import React, { useState } from 'react';
import geminiService from '../services/geminiService';
import LoadingSpinner from './LoadingSpinner';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateImage = async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt to generate an image.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setGeneratedImageUrl(null);

    try {
      const imageUrl = await geminiService.generateImage(prompt);
      setGeneratedImageUrl(imageUrl);
    } catch (err: any) {
      console.error('Error generating image:', err);
      setError(`Failed to generate image: ${err.message || 'Unknown error'}. Please try again.`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="p-6 bg-gray-800/60 backdrop-blur-lg rounded-2xl shadow-lg max-w-2xl mx-auto my-6 animate-fade-in text-gray-100">
      <h2 className="text-3xl font-bold text-gray-100 mb-4 border-b border-gray-700 pb-3 flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 mr-2 text-violet-400" viewBox="0 0 20 20" fill="currentColor">
          <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-4 3 3 5-5V15zm0-12H4v2h12V3z" clipRule="evenodd" />
        </svg>
        Image Generator
      </h2>
      <p className="text-gray-300 mb-6 text-lg">Unleash your creativity! Describe the image you want Chef Fridge to visualize.</p>

      <div className="mb-6">
        <textarea
          className="w-full p-4 border border-gray-600 rounded-xl focus:ring-violet-400 focus:border-violet-400 resize-y min-h-[120px] text-base bg-gray-900 text-gray-100"
          placeholder="A vibrant bowl of ramen with a perfectly cooked egg and fresh scallions, hyperrealistic, studio lighting."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          rows={5}
          aria-label="Image generation prompt"
        ></textarea>
      </div>

      <button
        onClick={handleGenerateImage}
        className="w-full bg-gradient-to-r from-violet-500 to-indigo-600 text-white font-bold py-3 px-4 rounded-xl hover:from-violet-600 hover:to-indigo-700 transition duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-md text-lg flex items-center justify-center"
        disabled={isLoading}
        aria-label="Generate image"
      >
        {isLoading ? (
          <>
            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-3"></div>
            Generating Image...
          </>
        ) : (
          <>
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16l4.016-4.016L16 16m-4 0l-4-4m4-4l4 4m4-4v12l-4-4m-4 4L4 16m4-4l4-4m4 4l4-4" />
            </svg>
            Generate Image
          </>
        )}
      </button>

      {error && (
        <p className="mt-4 text-rose-400 text-center text-sm">{error}</p>
      )}

      {isLoading && (
        <div className="mt-6">
          <LoadingSpinner message="Crafting your visual masterpiece..." />
        </div>
      )}

      {generatedImageUrl && (
        <div className="mt-8 border border-gray-700 rounded-2xl p-4 bg-gray-900/50 backdrop-blur-md">
          <h3 className="text-xl font-bold text-gray-100 mb-4 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-2 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-4 3 3 5-5V15zm0-12H4v2h12V3z" clipRule="evenodd" />
            </svg>
            Your Creation:
          </h3>
          <img
            src={generatedImageUrl}
            alt="Generated by AI"
            className="max-w-full h-auto rounded-xl shadow-lg mx-auto"
            loading="lazy"
          />
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;