import React, { useState } from 'react';
import geminiService from '../services/geminiService';
import LoadingSpinner from './LoadingSpinner';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateImage = async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt to generate an image.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setGeneratedImageUrl(null);

    try {
      const imageUrl = await geminiService.generateImage(prompt);
      setGeneratedImageUrl(imageUrl);
    } catch (err: any) {
      console.error('Error generating image:', err);
      setError(`Failed to generate image: ${err.message || 'Unknown error'}. Please try again.`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow-md max-w-2xl mx-auto my-6">
      <h2 className="text-2xl font-bold text-gray-800 mb-4 border-b pb-2">Image Generator</h2>
      <p className="text-gray-600 mb-4">Unleash your creativity! Describe the image you want to see.</p>

      <div className="mb-4">
        <textarea
          className="w-full p-3 border border-gray-300 rounded-md focus:ring-green-500 focus:border-green-500 resize-y min-h-[100px]"
          placeholder="A futuristic city at sunset, with flying cars and towering skyscrapers."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          rows={4}
        ></textarea>
      </div>

      <button
        onClick={handleGenerateImage}
        className="w-full bg-indigo-600 text-white font-semibold py-2 px-4 rounded-md hover:bg-indigo-700 transition duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
        disabled={isLoading}
      >
        {isLoading ? 'Generating...' : 'Generate Image'}
      </button>

      {error && (
        <p className="mt-4 text-red-600 text-center">{error}</p>
      )}

      {isLoading && (
        <div className="mt-6">
          <LoadingSpinner message="Generating your image..." />
        </div>
      )}

      {generatedImageUrl && (
        <div className="mt-6 border border-gray-200 rounded-lg p-2">
          <h3 className="text-xl font-semibold text-gray-700 mb-3">Generated Image:</h3>
          <img
            src={generatedImageUrl}
            alt="Generated by AI"
            className="max-w-full h-auto rounded-md shadow-lg"
          />
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;